# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --force
    # - run: npm run build --if-present
    # - run: npm test 
  docker:
      name: Deploy Docker Image
      runs-on: ubuntu-latest
      needs: build
      env:
        REPO: ${{secrets.DOCKER_REPO}}
      steps:
      - uses: actions/checkout@v3
      - run: echo ls
      - name: Docker Hub Sign-in 
        run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Building Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} ./
      - name: Publish Docker Image
        run: docker push $REPO
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: docker
    steps: 
      - name: Test ssh-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
          
            docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PASSWORD}}
            docker pull typoon0820/shopping_front
            cd shopping
            ./deploy_front.sh
